title: <p align="center"> Pavan Andagi </p>
logo: /assets/img/Pavan_pic.jpg

description:
  <p align="center">
  <a href="www.linkedin.com/in/pavan-andagi-02133610a/">LinkedIn</a> |
  <a href="https://github.com/pavanandagi">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
